language: go

dist: focal

go:
    - "1.16.x"

branches:
  only:
  - master
  - stable

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8361
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - sudo apt-get install python3-pytest

script:
- make install
- make test
- make smoke
- make irctest
